name: simple_canvas
description: "A Flutter project for a text editor assignment."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^6.3.2
  path_provider: ^2.1.3
  sqflite: ^2.4.2
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter-Regular.ttf
          - asset: assets/fonts/Inter-Italic.ttf
            style: italic
          - asset: assets/fonts/Inter-Bold.ttf
            weight: 700

      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Italic.ttf
            style: italic
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 700

      - family: Lato
        fonts:
          - asset: assets/fonts/Lato-Regular.ttf
          - asset: assets/fonts/Lato-Italic.ttf
            style: italic
          - asset: assets/fonts/Lato-Bold.ttf
            weight: 700

      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat-Italic.ttf
            style: italic
          - asset: assets/fonts/Montserrat-Bold.ttf
            weight: 700

      - family: Oswald
        fonts:
          - asset: assets/fonts/Oswald-Regular.ttf
          - asset: assets/fonts/Oswald-Italic.ttf
            style: italic
          - asset: assets/fonts/Oswald-Bold.ttf
            weight: 700

      - family: Source Code Pro
        fonts:
          - asset: assets/fonts/SourceCodePro-Regular.ttf
          - asset: assets/fonts/SourceCodePro-Italic.ttf
            style: italic
          - asset: assets/fonts/SourceCodePro-Bold.ttf
            weight: 700